modLoader = "javafml" #mandatory
loaderVersion = "[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU LGPL 3.0"
issueTrackerURL = "https://github.com/Schauweg/Smooth-Swapping/issues"

[[mods]] #mandatory
modId = "smoothswapping" #mandatory
version = "${version}" #mandatory
displayName = "Smooth Swapping" #mandatory
logoFile = "assets/smoothswapping/icon.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Schauweg" #optional
description = '''
Moves items smoothly in inventories
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.smoothswapping]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[45,)" #mandatory
ordering = "NONE"
side = "BOTH"

# Here's another dependency
[[dependencies.smoothswapping]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
